{{- define "users.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}-deployment
  labels:
    app: {{ .appName }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
    spec:
      containers:
      - name: {{ .appName }}
        image: {{ .container.image.name }}:{{ .container.image.version }}
        ports:
          - containerPort: {{ .container.port }}
        resources:
          request:
            memory: 256M  #256MB
            cpu: 100m     #10% of total cpu capacity
          limits:
            memory: 512M  #512MB
            cpu: 200m     #20% of total cpu capacity
{{- if .container.env }}
        env:              #indent 8 adds 8 spaces
{{ toYaml .container.env | indent 8 }}
{{- end }}
{{- end }}

---

{{- define "users.service" }}
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
spec:
  {{ if .service.type }}type: {{ .service.type }} {{ end }}
  selector:
    app: {{ .appName }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
      {{ if .service.nodePort }}nodePort: {{ .service.nodePort }} {{ end }}
{{- end }}
{{- end }}