apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.container.image }}
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.base.config }}
                key: postgres_db_host
          - name: POSTGRES_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.base.config }}
                key: postgres_db_port

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.ingress.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.ingress.service.port }}
      targetPort: 8080
