base:
  config: &configMap users-test-config
  namespace: &namespace users-test

apps:
  backend:
    namespace: *namespace
    host: users-test.local
    replicaCount: 1
    container:
      image:
        name: yuryli/k8s-users-app
        version: 11
  db:
    appName: users-pg-db
    namespace: *namespace
    replicaCount: 1
    container:
      image:
        name: yuryli/k8s-users-pg-db
        version: 14.6
    service:
      nodePort: 30043
